'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class English
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NHLGames.English", GetType(English).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear.
        '''</summary>
        Friend Shared ReadOnly Property btnClearConsole() As String
            Get
                Return ResourceManager.GetString("btnClearConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy to Clipboard.
        '''</summary>
        Friend Shared ReadOnly Property btnCopyConsole() As String
            Get
                Return ResourceManager.GetString("btnCopyConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add the NHL.tv authentication bypass line to Hosts file.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsAdd() As String
            Get
                Return ResourceManager.GetString("cbHostsAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy to clipboard the authentication bypass line.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsEntry() As String
            Get
                Return ResourceManager.GetString("cbHostsEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Hosts file location.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsLocation() As String
            Get
                Return ResourceManager.GetString("cbHostsLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove the NHL.tv authentication bypass line from Hosts file.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsRemove() As String
            Get
                Return ResourceManager.GetString("cbHostsRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test if the NHL.tv authentication bypass works.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsTest() As String
            Get
                Return ResourceManager.GetString("cbHostsTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Hosts file content in Notepad.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsView() As String
            Get
                Return ResourceManager.GetString("cbHostsView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Good - 504p - 950Mb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGood() As String
            Get
                Return ResourceManager.GetString("cbQualityGood", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Great - 540p - 1.3Gb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGreat() As String
            Get
                Return ResourceManager.GetString("cbQualityGreat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Low - 288p - 500Mb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityLow() As String
            Get
                Return ResourceManager.GetString("cbQualityLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile - 224p - 300Mb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityMobile() As String
            Get
                Return ResourceManager.GetString("cbQualityMobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal - 360p - 700Mb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityNormal() As String
            Get
                Return ResourceManager.GetString("cbQualityNormal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Superb - 720p - 1.8Gb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excellent - 720p @ 60 fps - 2.5Gb/hour.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb60fps() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb60fps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Try with the detected media player.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyAnyMediaPlayer() As String
            Get
                Return ResourceManager.GetString("chkSpotifyAnyMediaPlayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Force to start.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyForceToStart() As String
            Get
                Return ResourceManager.GetString("chkSpotifyForceToStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always play next song.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyPlayNextSong() As String
            Get
                Return ResourceManager.GetString("chkSpotifyPlayNextSong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ending.
        '''</summary>
        Friend Shared ReadOnly Property enumending() As String
            Get
                Return ResourceManager.GetString("enumending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property enumfinal() As String
            Get
                Return ResourceManager.GetString("enumfinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In progress.
        '''</summary>
        Friend Shared ReadOnly Property enuminprogress() As String
            Get
                Return ResourceManager.GetString("enuminprogress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pregame.
        '''</summary>
        Friend Shared ReadOnly Property enumpregame() As String
            Get
                Return ResourceManager.GetString("enumpregame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scheduled.
        '''</summary>
        Friend Shared ReadOnly Property enumscheduled() As String
            Get
                Return ResourceManager.GetString("enumscheduled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [cli].
        '''</summary>
        Friend Shared ReadOnly Property errorCliStreamer() As String
            Get
                Return ResourceManager.GetString("errorCliStreamer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error : Failed to deserialize setting value of &apos;{0}&apos; to type &apos;{1}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property errorDeserialize() As String
            Get
                Return ResourceManager.GetString("errorDeserialize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to error:.
        '''</summary>
        Friend Shared ReadOnly Property errorDetection() As String
            Get
                Return ResourceManager.GetString("errorDetection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to :.
        '''</summary>
        Friend Shared ReadOnly Property errorDoubleDot() As String
            Get
                Return ResourceManager.GetString("errorDoubleDot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to exception.
        '''</summary>
        Friend Shared ReadOnly Property errorExceptionDetection() As String
            Get
                Return ResourceManager.GetString("errorExceptionDetection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Failed to fetch games schedule..
        '''</summary>
        Friend Shared ReadOnly Property errorFetchingGames() As String
            Get
                Return ResourceManager.GetString("errorFetchingGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Code failed at: {0} - With exception: {1}.
        '''</summary>
        Friend Shared ReadOnly Property errorGeneral() As String
            Get
                Return ResourceManager.GetString("errorGeneral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Game stream {0} not found on the server.
        '''</summary>
        Friend Shared ReadOnly Property errorGettingStream() As String
            Get
                Return ResourceManager.GetString("errorGettingStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Game stream {0} not found on the server: {1}.
        '''</summary>
        Friend Shared ReadOnly Property errorGettingStreamWithEx() As String
            Get
                Return ResourceManager.GetString("errorGettingStreamWithEx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Selected Hostname is unreachable.
        '''</summary>
        Friend Shared ReadOnly Property errorHostname() As String
            Get
                Return ResourceManager.GetString("errorHostname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Can&apos;t find mpv.exe : mpv is a media player that we shipped with NHLGames. You probably moved it or deleted it. Please set a player, NHLGames needs one..
        '''</summary>
        Friend Shared ReadOnly Property errorMpvExe() As String
            Get
                Return ResourceManager.GetString("errorMpvExe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: No media player selected in settings..
        '''</summary>
        Friend Shared ReadOnly Property errorPlayerPathEmpty() As String
            Get
                Return ResourceManager.GetString("errorPlayerPathEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Failed to read app setting: {0}.
        '''</summary>
        Friend Shared ReadOnly Property errorReadingSettings() As String
            Get
                Return ResourceManager.GetString("errorReadingSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Can&apos;t set Ad Detection Modules. Verify if a Nugget package has a dependency of an older nugget package that you have installed (ex: Spotify and Json): {0}.
        '''</summary>
        Friend Shared ReadOnly Property errorSetAdModule() As String
            Get
                Return ResourceManager.GetString("errorSetAdModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error:  Can&apos;t find the specified streamer. The streamer is used to send streams to your media player, please select the one that comes with NHLGames or select a valid path of Livestreamer.exe or Streamlink.exe.
        '''</summary>
        Friend Shared ReadOnly Property errorStreamerExe() As String
            Get
                Return ResourceManager.GetString("errorStreamerExe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Starting stream failed. Make sure your player and streamer are set or try to use a different quality in settings, so it will try another stream..
        '''</summary>
        Friend Shared ReadOnly Property errorStreamFailed() As String
            Get
                Return ResourceManager.GetString("errorStreamFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Unable to decode url from NHL API, the structure has changed. We will have to fix this..
        '''</summary>
        Friend Shared ReadOnly Property errorUnableToDecodeJson() As String
            Get
                Return ResourceManager.GetString("errorUnableToDecodeJson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to unknown (server is not available).
        '''</summary>
        Friend Shared ReadOnly Property errorUnknownServerDown() As String
            Get
                Return ResourceManager.GetString("errorUnknownServerDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to warning:.
        '''</summary>
        Friend Shared ReadOnly Property errorWarning() As String
            Get
                Return ResourceManager.GetString("errorWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Failed to write app settings.
        '''</summary>
        Friend Shared ReadOnly Property errorWritingSettings() As String
            Get
                Return ResourceManager.GetString("errorWritingSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1st.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod1() As String
            Get
                Return ResourceManager.GetString("gamePeriod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2nd.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod2() As String
            Get
                Return ResourceManager.GetString("gamePeriod2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3rd.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod3() As String
            Get
                Return ResourceManager.GetString("gamePeriod3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodFinal() As String
            Get
                Return ResourceManager.GetString("gamePeriodFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OT.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOt() As String
            Get
                Return ResourceManager.GetString("gamePeriodOt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}OT.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOtMore() As String
            Get
                Return ResourceManager.GetString("gamePeriodOtMore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SO.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodSo() As String
            Get
                Return ResourceManager.GetString("gamePeriodSo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to leads.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesLead() As String
            Get
                Return ResourceManager.GetString("gameSeriesLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tied.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesTied() As String
            Get
                Return ResourceManager.GetString("gameSeriesTied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wins.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesWin() As String
            Get
                Return ResourceManager.GetString("gameSeriesWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use the alternate network.
        '''</summary>
        Friend Shared ReadOnly Property lblAlternateCdn() As String
            Get
                Return ResourceManager.GetString("lblAlternateCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Away Team : {0} {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblAwayTeam() As String
            Get
                Return ResourceManager.GetString("lblAwayTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} camera views.
        '''</summary>
        Friend Shared ReadOnly Property lblCamViews() As String
            Get
                Return ResourceManager.GetString("lblCamViews", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Content Delivery Network.
        '''</summary>
        Friend Shared ReadOnly Property lblCdn() As String
            Get
                Return ResourceManager.GetString("lblCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} endzone camera.
        '''</summary>
        Friend Shared ReadOnly Property lblEndzoneCam() As String
            Get
                Return ResourceManager.GetString("lblEndzoneCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property lblEnglish() As String
            Get
                Return ResourceManager.GetString("lblEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}, {1} {2}, {3}.
        '''</summary>
        Friend Shared ReadOnly Property lblFormatWeekMonthDayYear() As String
            Get
                Return ResourceManager.GetString("lblFormatWeekMonthDayYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Français.
        '''</summary>
        Friend Shared ReadOnly Property lblFrench() As String
            Get
                Return ResourceManager.GetString("lblFrench", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to French Canadian stream.
        '''</summary>
        Friend Shared ReadOnly Property lblFrenchNetwork() As String
            Get
                Return ResourceManager.GetString("lblFrenchNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblGame() As String
            Get
                Return ResourceManager.GetString("lblGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GM {0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblGameAbv() As String
            Get
                Return ResourceManager.GetString("lblGameAbv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Panel.
        '''</summary>
        Friend Shared ReadOnly Property lblGamePanel() As String
            Get
                Return ResourceManager.GetString("lblGamePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home Team : {0} {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblHomeTeam() As String
            Get
                Return ResourceManager.GetString("lblHomeTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHL.tv bypass failed.
        '''</summary>
        Friend Shared ReadOnly Property lblHostFileNotWorking() As String
            Get
                Return ResourceManager.GetString("lblHostFileNotWorking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server&apos;s Hostname.
        '''</summary>
        Friend Shared ReadOnly Property lblHostname() As String
            Get
                Return ResourceManager.GetString("lblHostname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts file.
        '''</summary>
        Friend Shared ReadOnly Property lblHosts() As String
            Get
                Return ResourceManager.GetString("lblHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property lblLanguage() As String
            Get
                Return ResourceManager.GetString("lblLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad detection.
        '''</summary>
        Friend Shared ReadOnly Property lblModules() As String
            Get
                Return ResourceManager.GetString("lblModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detect ads and notify activated apps below.
        '''</summary>
        Friend Shared ReadOnly Property lblModulesDesc() As String
            Get
                Return ResourceManager.GetString("lblModulesDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPC Path.
        '''</summary>
        Friend Shared ReadOnly Property lblMpcPath() As String
            Get
                Return ResourceManager.GetString("lblMpcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPV Path.
        '''</summary>
        Friend Shared ReadOnly Property lblMpvPath() As String
            Get
                Return ResourceManager.GetString("lblMpvPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to National stream.
        '''</summary>
        Friend Shared ReadOnly Property lblNationalNetwork() As String
            Get
                Return ResourceManager.GetString("lblNationalNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No game found.
        '''</summary>
        Friend Shared ReadOnly Property lblNoGames() As String
            Get
                Return ResourceManager.GetString("lblNoGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No stream available.
        '''</summary>
        Friend Shared ReadOnly Property lblNoStreamAvailable() As String
            Get
                Return ResourceManager.GetString("lblNoStreamAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OBS.
        '''</summary>
        Friend Shared ReadOnly Property lblObs() As String
            Get
                Return ResourceManager.GetString("lblObs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad ending hotkey.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdEndingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdEndingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad starting hotkey.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdStartingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdStartingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Switch scenes using binded keys when an Ad is detected.
        '''</summary>
        Friend Shared ReadOnly Property lblObsDesc() As String
            Get
                Return ResourceManager.GetString("lblObsDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  on {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblOnNetwork() As String
            Get
                Return ResourceManager.GetString("lblOnNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output.
        '''</summary>
        Friend Shared ReadOnly Property lblOutput() As String
            Get
                Return ResourceManager.GetString("lblOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Player.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayer() As String
            Get
                Return ResourceManager.GetString("lblPlayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Players Args.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayerArgs() As String
            Get
                Return ResourceManager.GetString("lblPlayerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preseason.
        '''</summary>
        Friend Shared ReadOnly Property lblPreseason() As String
            Get
                Return ResourceManager.GetString("lblPreseason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stream Quality.
        '''</summary>
        Friend Shared ReadOnly Property lblQuality() As String
            Get
                Return ResourceManager.GetString("lblQuality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Referee camera.
        '''</summary>
        Friend Shared ReadOnly Property lblRefCam() As String
            Get
                Return ResourceManager.GetString("lblRefCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final scores.
        '''</summary>
        Friend Shared ReadOnly Property lblShowFinalScores() As String
            Get
                Return ResourceManager.GetString("lblShowFinalScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live scores.
        '''</summary>
        Friend Shared ReadOnly Property lblShowLiveScores() As String
            Get
                Return ResourceManager.GetString("lblShowLiveScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Series record.
        '''</summary>
        Friend Shared ReadOnly Property lblShowSeriesRecord() As String
            Get
                Return ResourceManager.GetString("lblShowSeriesRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teams city abbreviation.
        '''</summary>
        Friend Shared ReadOnly Property lblShowTeamCityAbr() As String
            Get
                Return ResourceManager.GetString("lblShowTeamCityAbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamer Path.
        '''</summary>
        Friend Shared ReadOnly Property lblSlPath() As String
            Get
                Return ResourceManager.GetString("lblSlPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spotify.
        '''</summary>
        Friend Shared ReadOnly Property lblSpotify() As String
            Get
                Return ResourceManager.GetString("lblSpotify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play/Pause Spotify when an Ad is detected.
        '''</summary>
        Friend Shared ReadOnly Property lblSpotifyDesc() As String
            Get
                Return ResourceManager.GetString("lblSpotifyDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streams available at game time.
        '''</summary>
        Friend Shared ReadOnly Property lblStreamAvailableAtGameTime() As String
            Get
                Return ResourceManager.GetString("lblStreamAvailableAtGameTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamer Args.
        '''</summary>
        Friend Shared ReadOnly Property lblStreamerArgs() As String
            Get
                Return ResourceManager.GetString("lblStreamerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} stream.
        '''</summary>
        Friend Shared ReadOnly Property lblTeamStream() As String
            Get
                Return ResourceManager.GetString("lblTeamStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VLC Path.
        '''</summary>
        Friend Shared ReadOnly Property lblVlcPath() As String
            Get
                Return ResourceManager.GetString("lblVlcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Today.
        '''</summary>
        Friend Shared ReadOnly Property lnkCalendarToday() As String
            Get
                Return ResourceManager.GetString("lnkCalendarToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Unexpected Exception: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgAdDetectionException() As String
            Get
                Return ResourceManager.GetString("msgAdDetectionException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Problem initializing tasks: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgAdDetectionProbInit() As String
            Get
                Return ResourceManager.GetString("msgAdDetectionProbInit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add our server to your hosts file.
        '''</summary>
        Friend Shared ReadOnly Property msgAddHost() As String
            Get
                Return ResourceManager.GetString("msgAddHost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The {0} file is now set back to Read Only.
        '''</summary>
        Friend Shared ReadOnly Property msgAddReadOnly() As String
            Get
                Return ResourceManager.GetString("msgAddReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts: Backing up file: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgBackingHostsFile() As String
            Get
                Return ResourceManager.GetString("msgBackingHostsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [CENSORED_STREAM_URL].
        '''</summary>
        Friend Shared ReadOnly Property msgCensoredStream() As String
            Get
                Return ResourceManager.GetString("msgCensoredStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version {0} is available! Changes: {1}{2}{3}.
        '''</summary>
        Friend Shared ReadOnly Property msgChangeLog() As String
            Get
                Return ResourceManager.GetString("msgChangeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts: Removing existing entries from hosts file.
        '''</summary>
        Friend Shared ReadOnly Property msgCleanHostsFile() As String
            Get
                Return ResourceManager.GetString("msgCleanHostsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{0}] .
        '''</summary>
        Friend Shared ReadOnly Property msgDateTimeNow() As String
            Get
                Return ResourceManager.GetString("msgDateTimeNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error happened! See the console for more details.{0}Click on [?] button in the top-right corner to view NHLGames documentation for quick support in the Support section (App and Player).{0}You can also copy the console log using &apos;Copy to clipboard&apos; button and paste it in a new thread on NHLGames subreddit for help. Use the link in the bottom-left corner to get there..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorGeneralText() As String
            Get
                Return ResourceManager.GetString("msgErrorGeneralText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failure.
        '''</summary>
        Friend Shared ReadOnly Property msgFailure() As String
            Get
                Return ResourceManager.GetString("msgFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fetching.
        '''</summary>
        Friend Shared ReadOnly Property msgFetching() As String
            Get
                Return ResourceManager.GetString("msgFetching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Games Found : {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgGamesFound() As String
            Get
                Return ResourceManager.GetString("msgGamesFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: Game schedule for {1} from NHL.tv.
        '''</summary>
        Friend Shared ReadOnly Property msgGettingSchedule() As String
            Get
                Return ResourceManager.GetString("msgGettingSchedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames needs to add a line to your Windows Hosts file so it can redirect NHL.tv streams properly. Do you let NHLGames add its hostname to this file?.
        '''</summary>
        Friend Shared ReadOnly Property msgHostnameSet() As String
            Get
                Return ResourceManager.GetString("msgHostnameSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The NHL.tv authentication bypass line &apos;&apos;{0}&apos;&apos; was copied to your clipboard. Use CTRL+V to paste it in your Hosts file..
        '''</summary>
        Friend Shared ReadOnly Property msgHostsCopyEntry() As String
            Get
                Return ResourceManager.GetString("msgHostsCopyEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts entry doesn&apos;t seem to be working :(.
        '''</summary>
        Friend Shared ReadOnly Property msgHostsFailure() As String
            Get
                Return ResourceManager.GetString("msgHostsFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts file looks good!.
        '''</summary>
        Friend Shared ReadOnly Property msgHostsSuccess() As String
            Get
                Return ResourceManager.GetString("msgHostsSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Games.
        '''</summary>
        Friend Shared ReadOnly Property msgLoadingGames() As String
            Get
                Return ResourceManager.GetString("msgLoadingGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Version Available.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionAvailable() As String
            Get
                Return ResourceManager.GetString("msgNewVersionAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new version is available, download the latest version {0} on /r/nhl_games.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionText() As String
            Get
                Return ResourceManager.GetString("msgNewVersionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad.
        '''</summary>
        Friend Shared ReadOnly Property msgObsAdWord() As String
            Get
                Return ResourceManager.GetString("msgObsAdWord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad Detection: OBS is changing to {0} scene.
        '''</summary>
        Friend Shared ReadOnly Property msgObsChangingScene() As String
            Get
                Return ResourceManager.GetString("msgObsChangingScene", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game.
        '''</summary>
        Friend Shared ReadOnly Property msgObsGameWord() As String
            Get
                Return ResourceManager.GetString("msgObsGameWord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: OBS {0} scene hotkey not set.
        '''</summary>
        Friend Shared ReadOnly Property msgObsHotkeyNotSet() As String
            Get
                Return ResourceManager.GetString("msgObsHotkeyNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OFF.
        '''</summary>
        Friend Shared ReadOnly Property msgOff() As String
            Get
                Return ResourceManager.GetString("msgOff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ON.
        '''</summary>
        Friend Shared ReadOnly Property msgOn() As String
            Get
                Return ResourceManager.GetString("msgOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refreshing.
        '''</summary>
        Friend Shared ReadOnly Property msgRefreshing() As String
            Get
                Return ResourceManager.GetString("msgRefreshing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: The {0} file is no longer Read Only.
        '''</summary>
        Friend Shared ReadOnly Property msgRemoveReadOnly() As String
            Get
                Return ResourceManager.GetString("msgRemoveReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admin Access Required.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdmin() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames is missing the required hosts file entry. Do you want to restart this application as an Administrator and add the required entry?.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdminText() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdminText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Failed to download the game schedule file from {0}. Second attempt..
        '''</summary>
        Friend Shared ReadOnly Property msgServerNoRespondTryingAgain() As String
            Get
                Return ResourceManager.GetString("msgServerNoRespondTryingAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Server {0} seems down.
        '''</summary>
        Friend Shared ReadOnly Property msgServerSeemsDown() As String
            Get
                Return ResourceManager.GetString("msgServerSeemsDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Setting updated for &apos;{0}&apos; to &apos;{1}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property msgSettingUpdated() As String
            Get
                Return ResourceManager.GetString("msgSettingUpdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Can&apos;t start Spotify: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyCantStart() As String
            Get
                Return ResourceManager.GetString("msgSpotifyCantStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Unexpected exception connecting to Spotify: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyException() As String
            Get
                Return ResourceManager.GetString("msgSpotifyException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Ad Detection: Spotify is not installed.
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyIsntInstalled() As String
            Get
                Return ResourceManager.GetString("msgSpotifyIsntInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad Detection: Spotify didn&apos;t connect in time, try again..
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyNotConnected() As String
            Get
                Return ResourceManager.GetString("msgSpotifyNotConnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ad Detection: Spotify isn&apos;t running. Trying to start it....
        '''</summary>
        Friend Shared ReadOnly Property msgSpotifyNotRunning() As String
            Get
                Return ResourceManager.GetString("msgSpotifyNotRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting: Streamer {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgStartingStreamer() As String
            Get
                Return ResourceManager.GetString("msgStartingStreamer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamer:.
        '''</summary>
        Friend Shared ReadOnly Property msgStreamer() As String
            Get
                Return ResourceManager.GetString("msgStreamer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streaming: {0} on {1} using {2} player.
        '''</summary>
        Friend Shared ReadOnly Property msgStreaming() As String
            Get
                Return ResourceManager.GetString("msgStreaming", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Success.
        '''</summary>
        Friend Shared ReadOnly Property msgSuccess() As String
            Get
                Return ResourceManager.GetString("msgSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} vs {1}.
        '''</summary>
        Friend Shared ReadOnly Property msgTeamVsTeam() As String
            Get
                Return ResourceManager.GetString("msgTeamVsTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test ability to write to this directory.
        '''</summary>
        Friend Shared ReadOnly Property msgTestTxtContent() As String
            Get
                Return ResourceManager.GetString("msgTestTxtContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} enable.
        '''</summary>
        Friend Shared ReadOnly Property msgThisEnable() As String
            Get
                Return ResourceManager.GetString("msgThisEnable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Value too large for display].
        '''</summary>
        Friend Shared ReadOnly Property msgValueTooLarge() As String
            Get
                Return ResourceManager.GetString("msgValueTooLarge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Hosts File.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHosts() As String
            Get
                Return ResourceManager.GetString("msgViewHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to view the changes NHLGames made to your Hosts file?.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHostsText() As String
            Get
                Return ResourceManager.GetString("msgViewHostsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Video On Demand Status: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgVOD() As String
            Get
                Return ResourceManager.GetString("msgVOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can&apos;t find NHLGames config file. You will have to reinstall NHLGames..
        '''</summary>
        Friend Shared ReadOnly Property noConfigFile() As String
            Get
                Return ResourceManager.GetString("noConfigFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Internet connection.
        '''</summary>
        Friend Shared ReadOnly Property noWebAccess() As String
            Get
                Return ResourceManager.GetString("noWebAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Console.
        '''</summary>
        Friend Shared ReadOnly Property tabConsole() As String
            Get
                Return ResourceManager.GetString("tabConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Games.
        '''</summary>
        Friend Shared ReadOnly Property tabGames() As String
            Get
                Return ResourceManager.GetString("tabGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modules.
        '''</summary>
        Friend Shared ReadOnly Property tabModules() As String
            Get
                Return ResourceManager.GetString("tabModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property tabSettings() As String
            Get
                Return ResourceManager.GetString("tabSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse.
        '''</summary>
        Friend Shared ReadOnly Property tipBrowse() As String
            Get
                Return ResourceManager.GetString("tipBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download MPC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetMpc() As String
            Get
                Return ResourceManager.GetString("tipGetMpc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download VLC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetVlc() As String
            Get
                Return ResourceManager.GetString("tipGetVlc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Execute action.
        '''</summary>
        Friend Shared ReadOnly Property tipHostsExecuteAction() As String
            Get
                Return ResourceManager.GetString("tipHostsExecuteAction", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
