'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class French
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NHLGames.French", GetType(French).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Effacer.
        '''</summary>
        Friend Shared ReadOnly Property btnClearConsole() As String
            Get
                Return ResourceManager.GetString("btnClearConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Copier au presse-papier.
        '''</summary>
        Friend Shared ReadOnly Property btnCopyConsole() As String
            Get
                Return ResourceManager.GetString("btnCopyConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter la ligne de redirection de l&apos;authentifcation à NHL.tv au fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsAdd() As String
            Get
                Return ResourceManager.GetString("cbHostsAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Copier dans le presse-papier la ligne de redirection.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsEntry() As String
            Get
                Return ResourceManager.GetString("cbHostsEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ouvrir l&apos;emplacement du fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsLocation() As String
            Get
                Return ResourceManager.GetString("cbHostsLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Retirer la ligne de redirection de l&apos;authentification à NHL.tv au fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsRemove() As String
            Get
                Return ResourceManager.GetString("cbHostsRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Tester si le contournement de l&apos;authentification à NHL.tv fonctionne.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsTest() As String
            Get
                Return ResourceManager.GetString("cbHostsTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voir le contenu du fichier Hosts dans bloc-notes.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsView() As String
            Get
                Return ResourceManager.GetString("cbHostsView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bonne - 504p - 950Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGood() As String
            Get
                Return ResourceManager.GetString("cbQualityGood", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Géniale - 540p - 1.3Gb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGreat() As String
            Get
                Return ResourceManager.GetString("cbQualityGreat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Basse - 288p - 500Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityLow() As String
            Get
                Return ResourceManager.GetString("cbQualityLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mobile - 224p - 300Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityMobile() As String
            Get
                Return ResourceManager.GetString("cbQualityMobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Moyenne - 360p - 700Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityNormal() As String
            Get
                Return ResourceManager.GetString("cbQualityNormal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Superbe - 720p - 1.8Gb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Excellente - 720p @ 60 fps - 2.5Gb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb60fps() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb60fps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Essaie avec le lecteur média détecté.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyAnyMediaPlayer() As String
            Get
                Return ResourceManager.GetString("chkSpotifyAnyMediaPlayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Forcer le démarrage.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyForceToStart() As String
            Get
                Return ResourceManager.GetString("chkSpotifyForceToStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Toujours jouer la prochaine chanson.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyPlayNextSong() As String
            Get
                Return ResourceManager.GetString("chkSpotifyPlayNextSong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En cours.
        '''</summary>
        Friend Shared ReadOnly Property enumending() As String
            Get
                Return ResourceManager.GetString("enumending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Terminé.
        '''</summary>
        Friend Shared ReadOnly Property enumfinal() As String
            Get
                Return ResourceManager.GetString("enumfinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En cours.
        '''</summary>
        Friend Shared ReadOnly Property enuminprogress() As String
            Get
                Return ResourceManager.GetString("enuminprogress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Avant-match.
        '''</summary>
        Friend Shared ReadOnly Property enumpregame() As String
            Get
                Return ResourceManager.GetString("enumpregame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à À venir.
        '''</summary>
        Friend Shared ReadOnly Property enumscheduled() As String
            Get
                Return ResourceManager.GetString("enumscheduled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 1ere.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod1() As String
            Get
                Return ResourceManager.GetString("gamePeriod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 2eme.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod2() As String
            Get
                Return ResourceManager.GetString("gamePeriod2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 3eme.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod3() As String
            Get
                Return ResourceManager.GetString("gamePeriod3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Terminé.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodFinal() As String
            Get
                Return ResourceManager.GetString("gamePeriodFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à P.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOt() As String
            Get
                Return ResourceManager.GetString("gamePeriodOt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {0}E P.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOtMore() As String
            Get
                Return ResourceManager.GetString("gamePeriodOtMore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à FUS.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodSo() As String
            Get
                Return ResourceManager.GetString("gamePeriodSo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mène.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesLead() As String
            Get
                Return ResourceManager.GetString("gameSeriesLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à égale.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesTied() As String
            Get
                Return ResourceManager.GetString("gameSeriesTied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à gagne.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesWin() As String
            Get
                Return ResourceManager.GetString("gameSeriesWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utiliser le réseau alternatif.
        '''</summary>
        Friend Shared ReadOnly Property lblAlternateCdn() As String
            Get
                Return ResourceManager.GetString("lblAlternateCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Visiteurs : {1} {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblAwayTeam() As String
            Get
                Return ResourceManager.GetString("lblAwayTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {0} vues de camera.
        '''</summary>
        Friend Shared ReadOnly Property lblCamViews() As String
            Get
                Return ResourceManager.GetString("lblCamViews", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Réseau de diffusion.
        '''</summary>
        Friend Shared ReadOnly Property lblCdn() As String
            Get
                Return ResourceManager.GetString("lblCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Caméra zone {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblEndzoneCam() As String
            Get
                Return ResourceManager.GetString("lblEndzoneCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à English.
        '''</summary>
        Friend Shared ReadOnly Property lblEnglish() As String
            Get
                Return ResourceManager.GetString("lblEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {0} {2} {1} {3}.
        '''</summary>
        Friend Shared ReadOnly Property lblFormatWeekMonthDayYear() As String
            Get
                Return ResourceManager.GetString("lblFormatWeekMonthDayYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Français.
        '''</summary>
        Friend Shared ReadOnly Property lblFrench() As String
            Get
                Return ResourceManager.GetString("lblFrench", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Stream canadien français.
        '''</summary>
        Friend Shared ReadOnly Property lblFrenchNetwork() As String
            Get
                Return ResourceManager.GetString("lblFrenchNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Match {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblGame() As String
            Get
                Return ResourceManager.GetString("lblGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à M{0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblGameAbv() As String
            Get
                Return ResourceManager.GetString("lblGameAbv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Panneau de partie.
        '''</summary>
        Friend Shared ReadOnly Property lblGamePanel() As String
            Get
                Return ResourceManager.GetString("lblGamePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Locaux : {1} {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblHomeTeam() As String
            Get
                Return ResourceManager.GetString("lblHomeTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de domaine.
        '''</summary>
        Friend Shared ReadOnly Property lblHostname() As String
            Get
                Return ResourceManager.GetString("lblHostname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property lblHosts() As String
            Get
                Return ResourceManager.GetString("lblHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Langue.
        '''</summary>
        Friend Shared ReadOnly Property lblLanguage() As String
            Get
                Return ResourceManager.GetString("lblLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Détection de publicité.
        '''</summary>
        Friend Shared ReadOnly Property lblModules() As String
            Get
                Return ResourceManager.GetString("lblModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Emplacement MPC.
        '''</summary>
        Friend Shared ReadOnly Property lblMpcPath() As String
            Get
                Return ResourceManager.GetString("lblMpcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Emplacement MPV.
        '''</summary>
        Friend Shared ReadOnly Property lblMpvPath() As String
            Get
                Return ResourceManager.GetString("lblMpvPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Stream national.
        '''</summary>
        Friend Shared ReadOnly Property lblNationalNetwork() As String
            Get
                Return ResourceManager.GetString("lblNationalNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun match trouvé.
        '''</summary>
        Friend Shared ReadOnly Property lblNoGames() As String
            Get
                Return ResourceManager.GetString("lblNoGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun stream de disponible.
        '''</summary>
        Friend Shared ReadOnly Property lblNoStreamAvailable() As String
            Get
                Return ResourceManager.GetString("lblNoStreamAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à OBS.
        '''</summary>
        Friend Shared ReadOnly Property lblObs() As String
            Get
                Return ResourceManager.GetString("lblObs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Raccourci clavier: Fin d&apos;annonce.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdEndingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdEndingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Raccourci clavier: Début d&apos;annonce.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdStartingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdStartingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Change de fenêtre selon les touches configurées quand une annonce est détectée.
        '''</summary>
        Friend Shared ReadOnly Property lblObsDesc() As String
            Get
                Return ResourceManager.GetString("lblObsDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à  sur {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblOnNetwork() As String
            Get
                Return ResourceManager.GetString("lblOnNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Enregistrement.
        '''</summary>
        Friend Shared ReadOnly Property lblOutput() As String
            Get
                Return ResourceManager.GetString("lblOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lecteur par défaut.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayer() As String
            Get
                Return ResourceManager.GetString("lblPlayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lecteur args. supp..
        '''</summary>
        Friend Shared ReadOnly Property lblPlayerArgs() As String
            Get
                Return ResourceManager.GetString("lblPlayerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Séries.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayoffs() As String
            Get
                Return ResourceManager.GetString("lblPlayoffs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Présaison.
        '''</summary>
        Friend Shared ReadOnly Property lblPreseason() As String
            Get
                Return ResourceManager.GetString("lblPreseason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Qualité vidéo.
        '''</summary>
        Friend Shared ReadOnly Property lblQuality() As String
            Get
                Return ResourceManager.GetString("lblQuality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Camera de l&apos;arbitre.
        '''</summary>
        Friend Shared ReadOnly Property lblRefCam() As String
            Get
                Return ResourceManager.GetString("lblRefCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Afficher les résultats finaux.
        '''</summary>
        Friend Shared ReadOnly Property lblShowFinalScores() As String
            Get
                Return ResourceManager.GetString("lblShowFinalScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Afficher les résultats en direct.
        '''</summary>
        Friend Shared ReadOnly Property lblShowLiveScores() As String
            Get
                Return ResourceManager.GetString("lblShowLiveScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Afficher les détails des séries.
        '''</summary>
        Friend Shared ReadOnly Property lblShowSeriesRecord() As String
            Get
                Return ResourceManager.GetString("lblShowSeriesRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Emplacement du Streamer.
        '''</summary>
        Friend Shared ReadOnly Property lblSlPath() As String
            Get
                Return ResourceManager.GetString("lblSlPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Spotify.
        '''</summary>
        Friend Shared ReadOnly Property lblSpotify() As String
            Get
                Return ResourceManager.GetString("lblSpotify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Résume/Pause Spotify quand une annonce est détectée.
        '''</summary>
        Friend Shared ReadOnly Property lblSpotifyDesc() As String
            Get
                Return ResourceManager.GetString("lblSpotifyDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Streams disponible à l&apos;heure du match.
        '''</summary>
        Friend Shared ReadOnly Property lblStreamAvailableAtGameTime() As String
            Get
                Return ResourceManager.GetString("lblStreamAvailableAtGameTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Streamer args. supp..
        '''</summary>
        Friend Shared ReadOnly Property lblStreamerArgs() As String
            Get
                Return ResourceManager.GetString("lblStreamerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {0} stream.
        '''</summary>
        Friend Shared ReadOnly Property lblTeamStream() As String
            Get
                Return ResourceManager.GetString("lblTeamStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Emplacement VLC.
        '''</summary>
        Friend Shared ReadOnly Property lblVlcPath() As String
            Get
                Return ResourceManager.GetString("lblVlcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aujourd&apos;hui.
        '''</summary>
        Friend Shared ReadOnly Property lnkCalendarToday() As String
            Get
                Return ResourceManager.GetString("lnkCalendarToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter l&apos;entrée du serveur au fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property msgAddHost() As String
            Get
                Return ResourceManager.GetString("msgAddHost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Version {0} maintenant disponible! Changements: {1}{2}{3}.
        '''</summary>
        Friend Shared ReadOnly Property msgChangeLog() As String
            Get
                Return ResourceManager.GetString("msgChangeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Une erreur est survenue! Voir la console pour plus de détails.{0}Cliquez sur le bouton [?] dans le coin supérieur droit pour voir la documentation en anglais de NHLGames et obtenir un support rapide dans la section &apos;Support&apos; (Application et Lecteur){0}Vous pouvez copier le contenu de la console avec le bouton &apos;Copier au presse-papier&apos; et coller (CTRL+V) dans un nouveau sujet sur reddit /r/NHLGames pour obtenir de l&apos;aide. Utilisez le lien en bas à gauche pour vous y rendre..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorGeneralText() As String
            Get
                Return ResourceManager.GetString("msgErrorGeneralText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Erreur.
        '''</summary>
        Friend Shared ReadOnly Property msgFailure() As String
            Get
                Return ResourceManager.GetString("msgFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Matchs trouvés : {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgGamesFound() As String
            Get
                Return ResourceManager.GetString("msgGamesFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à NHLGames ne peut pas fonctionner sans avoir son nom de domaine inscrit dans le fichier Hosts de Windows. Acceptez-vous que NHLGames ajoute une entrée à votre fichier Hosts, ainsi Windows pourra résoudre le nom de domaine de NHLGames et pourra se connecter à son adresse IP?.
        '''</summary>
        Friend Shared ReadOnly Property msgHostnameSet() As String
            Get
                Return ResourceManager.GetString("msgHostnameSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La ligne de redirection de l&apos;authentifcation à NHL.tv &apos;&apos;{0}&apos;&apos; a été copiée dans votre presse-papier. Utiliser CTRL+V pour la coller dans le fichier Hosts..
        '''</summary>
        Friend Shared ReadOnly Property msgHostsCopyEntry() As String
            Get
                Return ResourceManager.GetString("msgHostsCopyEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;entrée dans le fichier Hosts ne semble pas fonctionner :(.
        '''</summary>
        Friend Shared ReadOnly Property msgHostsFailure() As String
            Get
                Return ResourceManager.GetString("msgHostsFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le fichier Hosts semble fonctionnel :).
        '''</summary>
        Friend Shared ReadOnly Property msgHostsSuccess() As String
            Get
                Return ResourceManager.GetString("msgHostsSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Chargement des matchs.
        '''</summary>
        Friend Shared ReadOnly Property msgLoadingGames() As String
            Get
                Return ResourceManager.GetString("msgLoadingGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nouvelle version disponible.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionAvailable() As String
            Get
                Return ResourceManager.GetString("msgNewVersionAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Une nouvelle version est disponible, téléchargez la plus récente version {0} sur /r/nhl_games.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionText() As String
            Get
                Return ResourceManager.GetString("msgNewVersionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Accès d&apos;administrateur requis.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdmin() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à NHLGames requiert une entrée au fichier Hosts qui est manquante. Voulez-vous qu&apos;elle redémarre avec le droit d&apos;administrateur et l&apos;ajoute l&apos;entrée manquante?.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdminText() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdminText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Succès.
        '''</summary>
        Friend Shared ReadOnly Property msgSuccess() As String
            Get
                Return ResourceManager.GetString("msgSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {0} vs {1}.
        '''</summary>
        Friend Shared ReadOnly Property msgTeamVsTeam() As String
            Get
                Return ResourceManager.GetString("msgTeamVsTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voir le fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHosts() As String
            Get
                Return ResourceManager.GetString("msgViewHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voulez-vous voir les changements apportés au fichier Hosts?.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHostsText() As String
            Get
                Return ResourceManager.GetString("msgViewHostsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fichier de configuration NHLGames introuvable. Vous devez réinstaller NHLGames..
        '''</summary>
        Friend Shared ReadOnly Property noConfigFile() As String
            Get
                Return ResourceManager.GetString("noConfigFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucune connexion internet.
        '''</summary>
        Friend Shared ReadOnly Property noWebAccess() As String
            Get
                Return ResourceManager.GetString("noWebAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Console.
        '''</summary>
        Friend Shared ReadOnly Property tabConsole() As String
            Get
                Return ResourceManager.GetString("tabConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Matchs.
        '''</summary>
        Friend Shared ReadOnly Property tabGames() As String
            Get
                Return ResourceManager.GetString("tabGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Modules.
        '''</summary>
        Friend Shared ReadOnly Property tabModules() As String
            Get
                Return ResourceManager.GetString("tabModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Paramètres.
        '''</summary>
        Friend Shared ReadOnly Property tabSettings() As String
            Get
                Return ResourceManager.GetString("tabSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parcourir.
        '''</summary>
        Friend Shared ReadOnly Property tipBrowse() As String
            Get
                Return ResourceManager.GetString("tipBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Download MPC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetMpc() As String
            Get
                Return ResourceManager.GetString("tipGetMpc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Download VLC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetVlc() As String
            Get
                Return ResourceManager.GetString("tipGetVlc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exécuter l&apos;action.
        '''</summary>
        Friend Shared ReadOnly Property tipHostsExecuteAction() As String
            Get
                Return ResourceManager.GetString("tipHostsExecuteAction", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
