'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class French
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NHLGames.French", GetType(French).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacer.
        '''</summary>
        Friend Shared ReadOnly Property btnClearConsole() As String
            Get
                Return ResourceManager.GetString("btnClearConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copier au presse-papier.
        '''</summary>
        Friend Shared ReadOnly Property btnCopyConsole() As String
            Get
                Return ResourceManager.GetString("btnCopyConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ajouter la ligne de redirection de l&apos;authentifcation à NHL.tv au fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsAdd() As String
            Get
                Return ResourceManager.GetString("cbHostsAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copier dans le presse-papier la ligne de redirection.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsEntry() As String
            Get
                Return ResourceManager.GetString("cbHostsEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ouvrir l&apos;emplacement du fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsLocation() As String
            Get
                Return ResourceManager.GetString("cbHostsLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retirer la ligne de redirection de l&apos;authentification à NHL.tv au fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsRemove() As String
            Get
                Return ResourceManager.GetString("cbHostsRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tester si le contournement de l&apos;authentification à NHL.tv fonctionne.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsTest() As String
            Get
                Return ResourceManager.GetString("cbHostsTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voir le contenu du fichier Hosts dans bloc-notes.
        '''</summary>
        Friend Shared ReadOnly Property cbHostsView() As String
            Get
                Return ResourceManager.GetString("cbHostsView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bonne - 504p - 950Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGood() As String
            Get
                Return ResourceManager.GetString("cbQualityGood", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Géniale - 540p - 1.3Gb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityGreat() As String
            Get
                Return ResourceManager.GetString("cbQualityGreat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Basse - 288p - 500Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityLow() As String
            Get
                Return ResourceManager.GetString("cbQualityLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile - 224p - 300Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityMobile() As String
            Get
                Return ResourceManager.GetString("cbQualityMobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moyenne - 360p - 700Mb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualityNormal() As String
            Get
                Return ResourceManager.GetString("cbQualityNormal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Superbe - 720p - 1.8Gb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excellente - 720p @ 60 fps - 2.5Gb/heure.
        '''</summary>
        Friend Shared ReadOnly Property cbQualitySuperb60fps() As String
            Get
                Return ResourceManager.GetString("cbQualitySuperb60fps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Essayer avec le lecteur média détecté.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyAnyMediaPlayer() As String
            Get
                Return ResourceManager.GetString("chkSpotifyAnyMediaPlayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forcer le démarrage.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyForceToStart() As String
            Get
                Return ResourceManager.GetString("chkSpotifyForceToStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Toujours jouer la prochaine chanson.
        '''</summary>
        Friend Shared ReadOnly Property chkSpotifyPlayNextSong() As String
            Get
                Return ResourceManager.GetString("chkSpotifyPlayNextSong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En cours.
        '''</summary>
        Friend Shared ReadOnly Property enumending() As String
            Get
                Return ResourceManager.GetString("enumending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminé.
        '''</summary>
        Friend Shared ReadOnly Property enumfinal() As String
            Get
                Return ResourceManager.GetString("enumfinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En cours.
        '''</summary>
        Friend Shared ReadOnly Property enuminprogress() As String
            Get
                Return ResourceManager.GetString("enuminprogress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Avant-match.
        '''</summary>
        Friend Shared ReadOnly Property enumpregame() As String
            Get
                Return ResourceManager.GetString("enumpregame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to À venir.
        '''</summary>
        Friend Shared ReadOnly Property enumscheduled() As String
            Get
                Return ResourceManager.GetString("enumscheduled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1ère.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod1() As String
            Get
                Return ResourceManager.GetString("gamePeriod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2ième.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod2() As String
            Get
                Return ResourceManager.GetString("gamePeriod2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3ième.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod3() As String
            Get
                Return ResourceManager.GetString("gamePeriod3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminé.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodFinal() As String
            Get
                Return ResourceManager.GetString("gamePeriodFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOt() As String
            Get
                Return ResourceManager.GetString("gamePeriodOt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}E P.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOtMore() As String
            Get
                Return ResourceManager.GetString("gamePeriodOtMore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FUS.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodSo() As String
            Get
                Return ResourceManager.GetString("gamePeriodSo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mène.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesLead() As String
            Get
                Return ResourceManager.GetString("gameSeriesLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to égale.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesTied() As String
            Get
                Return ResourceManager.GetString("gameSeriesTied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gagne.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesWin() As String
            Get
                Return ResourceManager.GetString("gameSeriesWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utiliser le réseau alternatif.
        '''</summary>
        Friend Shared ReadOnly Property lblAlternateCdn() As String
            Get
                Return ResourceManager.GetString("lblAlternateCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Visiteurs : {1} {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblAwayTeam() As String
            Get
                Return ResourceManager.GetString("lblAwayTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} vues de caméra.
        '''</summary>
        Friend Shared ReadOnly Property lblCamViews() As String
            Get
                Return ResourceManager.GetString("lblCamViews", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Réseau de diffusion.
        '''</summary>
        Friend Shared ReadOnly Property lblCdn() As String
            Get
                Return ResourceManager.GetString("lblCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Caméra zone {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblEndzoneCam() As String
            Get
                Return ResourceManager.GetString("lblEndzoneCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property lblEnglish() As String
            Get
                Return ResourceManager.GetString("lblEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} {2} {1} {3}.
        '''</summary>
        Friend Shared ReadOnly Property lblFormatWeekMonthDayYear() As String
            Get
                Return ResourceManager.GetString("lblFormatWeekMonthDayYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Français.
        '''</summary>
        Friend Shared ReadOnly Property lblFrench() As String
            Get
                Return ResourceManager.GetString("lblFrench", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stream canadien français.
        '''</summary>
        Friend Shared ReadOnly Property lblFrenchNetwork() As String
            Get
                Return ResourceManager.GetString("lblFrenchNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Match {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblGame() As String
            Get
                Return ResourceManager.GetString("lblGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M{0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblGameAbv() As String
            Get
                Return ResourceManager.GetString("lblGameAbv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panneau de partie.
        '''</summary>
        Friend Shared ReadOnly Property lblGamePanel() As String
            Get
                Return ResourceManager.GetString("lblGamePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Locaux : {1} {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblHomeTeam() As String
            Get
                Return ResourceManager.GetString("lblHomeTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Redirection NHL.tv impossible.
        '''</summary>
        Friend Shared ReadOnly Property lblHostFileNotWorking() As String
            Get
                Return ResourceManager.GetString("lblHostFileNotWorking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom de domaine.
        '''</summary>
        Friend Shared ReadOnly Property lblHostname() As String
            Get
                Return ResourceManager.GetString("lblHostname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property lblHosts() As String
            Get
                Return ResourceManager.GetString("lblHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Langue.
        '''</summary>
        Friend Shared ReadOnly Property lblLanguage() As String
            Get
                Return ResourceManager.GetString("lblLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Détection de publicité.
        '''</summary>
        Friend Shared ReadOnly Property lblModules() As String
            Get
                Return ResourceManager.GetString("lblModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Détecte les annonces et informe les applications activées ci-dessous.
        '''</summary>
        Friend Shared ReadOnly Property lblModulesDesc() As String
            Get
                Return ResourceManager.GetString("lblModulesDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement MPC.
        '''</summary>
        Friend Shared ReadOnly Property lblMpcPath() As String
            Get
                Return ResourceManager.GetString("lblMpcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement MPV.
        '''</summary>
        Friend Shared ReadOnly Property lblMpvPath() As String
            Get
                Return ResourceManager.GetString("lblMpvPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stream national.
        '''</summary>
        Friend Shared ReadOnly Property lblNationalNetwork() As String
            Get
                Return ResourceManager.GetString("lblNationalNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aucun match trouvé.
        '''</summary>
        Friend Shared ReadOnly Property lblNoGames() As String
            Get
                Return ResourceManager.GetString("lblNoGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streams indisponible.
        '''</summary>
        Friend Shared ReadOnly Property lblNoStreamAvailable() As String
            Get
                Return ResourceManager.GetString("lblNoStreamAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OBS.
        '''</summary>
        Friend Shared ReadOnly Property lblObs() As String
            Get
                Return ResourceManager.GetString("lblObs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raccourci clavier: Fin d&apos;annonce.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdEndingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdEndingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raccourci clavier: Début d&apos;annonce.
        '''</summary>
        Friend Shared ReadOnly Property lblObsAdStartingHotkey() As String
            Get
                Return ResourceManager.GetString("lblObsAdStartingHotkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change de fenêtre selon les touches configurées quand une annonce est détectée.
        '''</summary>
        Friend Shared ReadOnly Property lblObsDesc() As String
            Get
                Return ResourceManager.GetString("lblObsDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  sur {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblOnNetwork() As String
            Get
                Return ResourceManager.GetString("lblOnNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enregistrement.
        '''</summary>
        Friend Shared ReadOnly Property lblOutput() As String
            Get
                Return ResourceManager.GetString("lblOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lecteur par défaut.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayer() As String
            Get
                Return ResourceManager.GetString("lblPlayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lecteur args. supp..
        '''</summary>
        Friend Shared ReadOnly Property lblPlayerArgs() As String
            Get
                Return ResourceManager.GetString("lblPlayerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Présaison.
        '''</summary>
        Friend Shared ReadOnly Property lblPreseason() As String
            Get
                Return ResourceManager.GetString("lblPreseason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qualité vidéo.
        '''</summary>
        Friend Shared ReadOnly Property lblQuality() As String
            Get
                Return ResourceManager.GetString("lblQuality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Caméra de l&apos;arbitre.
        '''</summary>
        Friend Shared ReadOnly Property lblRefCam() As String
            Get
                Return ResourceManager.GetString("lblRefCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Résultats finaux.
        '''</summary>
        Friend Shared ReadOnly Property lblShowFinalScores() As String
            Get
                Return ResourceManager.GetString("lblShowFinalScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Résultats en direct.
        '''</summary>
        Friend Shared ReadOnly Property lblShowLiveScores() As String
            Get
                Return ResourceManager.GetString("lblShowLiveScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Détails des séries.
        '''</summary>
        Friend Shared ReadOnly Property lblShowSeriesRecord() As String
            Get
                Return ResourceManager.GetString("lblShowSeriesRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abbréviation de la ville des équipes.
        '''</summary>
        Friend Shared ReadOnly Property lblShowTeamCityAbr() As String
            Get
                Return ResourceManager.GetString("lblShowTeamCityAbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parties en direct en premier.
        '''</summary>
        Friend Shared ReadOnly Property lblShowTodayLiveGamesFirst() As String
            Get
                Return ResourceManager.GetString("lblShowTodayLiveGamesFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement du Streamer.
        '''</summary>
        Friend Shared ReadOnly Property lblSlPath() As String
            Get
                Return ResourceManager.GetString("lblSlPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spotify.
        '''</summary>
        Friend Shared ReadOnly Property lblSpotify() As String
            Get
                Return ResourceManager.GetString("lblSpotify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Joue/Pause Spotify quand une annonce est détectée.
        '''</summary>
        Friend Shared ReadOnly Property lblSpotifyDesc() As String
            Get
                Return ResourceManager.GetString("lblSpotifyDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Caméra du joueur.
        '''</summary>
        Friend Shared ReadOnly Property lblStarCam() As String
            Get
                Return ResourceManager.GetString("lblStarCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streams disponible à l&apos;heure du match.
        '''</summary>
        Friend Shared ReadOnly Property lblStreamAvailableAtGameTime() As String
            Get
                Return ResourceManager.GetString("lblStreamAvailableAtGameTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamer args. supp..
        '''</summary>
        Friend Shared ReadOnly Property lblStreamerArgs() As String
            Get
                Return ResourceManager.GetString("lblStreamerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} stream.
        '''</summary>
        Friend Shared ReadOnly Property lblTeamStream() As String
            Get
                Return ResourceManager.GetString("lblTeamStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emplacement VLC.
        '''</summary>
        Friend Shared ReadOnly Property lblVlcPath() As String
            Get
                Return ResourceManager.GetString("lblVlcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aujourd&apos;hui.
        '''</summary>
        Friend Shared ReadOnly Property lnkCalendarToday() As String
            Get
                Return ResourceManager.GetString("lnkCalendarToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ajouter l&apos;entrée du serveur au fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property msgAddHost() As String
            Get
                Return ResourceManager.GetString("msgAddHost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annonce!.
        '''</summary>
        Friend Shared ReadOnly Property msgAnnouncement() As String
            Get
                Return ResourceManager.GetString("msgAnnouncement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version {0} maintenant disponible! Changements: {1}{2}{3}.
        '''</summary>
        Friend Shared ReadOnly Property msgChangeLog() As String
            Get
                Return ResourceManager.GetString("msgChangeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Une erreur est survenue!{0}Cliquez sur [?] (coin supérieur droit) pour voir la documentation en anglais de NHLGames et rechercher votre problème{0}Si introuvable, cliquez sur &quot;Copier au presse-papier&quot; et collez dans un nouveau sujet sur /r/nhl_games ou ouvrez un &quot;issue&quot; sur notre page GitHub. Soyez certain qu&apos;aucun sujet (thread) n&apos;y réfère déjà..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorGeneralText() As String
            Get
                Return ResourceManager.GetString("msgErrorGeneralText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur.
        '''</summary>
        Friend Shared ReadOnly Property msgFailure() As String
            Get
                Return ResourceManager.GetString("msgFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Matchs trouvés : {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgGamesFound() As String
            Get
                Return ResourceManager.GetString("msgGamesFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames doit ajouter une ligne à votre fichier Hosts de Windows pour qu&apos;il puisse rediriger efficacement les streams de NHL.tv. Laissez-vous NHLGames ajouter son domaine à ce fichier?.
        '''</summary>
        Friend Shared ReadOnly Property msgHostnameSet() As String
            Get
                Return ResourceManager.GetString("msgHostnameSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La ligne de redirection de l&apos;authentifcation à NHL.tv &apos;&apos;{0}&apos;&apos; a été copiée dans votre presse-papier. Utiliser CTRL+V pour la coller dans le fichier Hosts..
        '''</summary>
        Friend Shared ReadOnly Property msgHostsCopyEntry() As String
            Get
                Return ResourceManager.GetString("msgHostsCopyEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;entrée dans le fichier Hosts ne semble pas fonctionner :(.
        '''</summary>
        Friend Shared ReadOnly Property msgHostsFailure() As String
            Get
                Return ResourceManager.GetString("msgHostsFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le fichier Hosts de Windows semble fonctionnel: Les adresses IP de NHL.tv et NHLGames correspondent  :).
        '''</summary>
        Friend Shared ReadOnly Property msgHostsSuccess() As String
            Get
                Return ResourceManager.GetString("msgHostsSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chargement des matchs.
        '''</summary>
        Friend Shared ReadOnly Property msgLoadingGames() As String
            Get
                Return ResourceManager.GetString("msgLoadingGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nouvelle version disponible.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionAvailable() As String
            Get
                Return ResourceManager.GetString("msgNewVersionAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Une nouvelle version est disponible, téléchargez la plus récente version {0} sur GitHub.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionText() As String
            Get
                Return ResourceManager.GetString("msgNewVersionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assurez-vous que votre antivirus n&apos;est pas effacé un fichier, sinon réinstallez l&apos;app. Voulez-vous quitter NHLGames?.
        '''</summary>
        Friend Shared ReadOnly Property msgNotStarting() As String
            Get
                Return ResourceManager.GetString("msgNotStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accès d&apos;administrateur requis.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdmin() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames requiert une entrée au fichier Hosts qui est manquante. Voulez-vous qu&apos;elle redémarre avec le droit d&apos;administrateur et l&apos;ajoute l&apos;entrée manquante?.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdminText() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdminText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Succès.
        '''</summary>
        Friend Shared ReadOnly Property msgSuccess() As String
            Get
                Return ResourceManager.GetString("msgSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} vs {1}.
        '''</summary>
        Friend Shared ReadOnly Property msgTeamVsTeam() As String
            Get
                Return ResourceManager.GetString("msgTeamVsTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voir le fichier Hosts.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHosts() As String
            Get
                Return ResourceManager.GetString("msgViewHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voulez-vous voir les changements apportés au fichier Hosts?.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHostsText() As String
            Get
                Return ResourceManager.GetString("msgViewHostsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames serveur non disponible!.
        '''</summary>
        Friend Shared ReadOnly Property noAppServer() As String
            Get
                Return ResourceManager.GetString("noAppServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aucun serveur de redirection trouvé!.
        '''</summary>
        Friend Shared ReadOnly Property noGameServer() As String
            Get
                Return ResourceManager.GetString("noGameServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aucun accès à Internet!.
        '''</summary>
        Friend Shared ReadOnly Property noWebAccess() As String
            Get
                Return ResourceManager.GetString("noWebAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Console.
        '''</summary>
        Friend Shared ReadOnly Property tabConsole() As String
            Get
                Return ResourceManager.GetString("tabConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Matchs.
        '''</summary>
        Friend Shared ReadOnly Property tabGames() As String
            Get
                Return ResourceManager.GetString("tabGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modules.
        '''</summary>
        Friend Shared ReadOnly Property tabModules() As String
            Get
                Return ResourceManager.GetString("tabModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paramètres.
        '''</summary>
        Friend Shared ReadOnly Property tabSettings() As String
            Get
                Return ResourceManager.GetString("tabSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stream brisé.
        '''</summary>
        Friend Shared ReadOnly Property tipBrokenStream() As String
            Get
                Return ResourceManager.GetString("tipBrokenStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parcourir.
        '''</summary>
        Friend Shared ReadOnly Property tipBrowse() As String
            Get
                Return ResourceManager.GetString("tipBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download MPC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetMpc() As String
            Get
                Return ResourceManager.GetString("tipGetMpc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download VLC.
        '''</summary>
        Friend Shared ReadOnly Property tipGetVlc() As String
            Get
                Return ResourceManager.GetString("tipGetVlc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exécuter l&apos;action.
        '''</summary>
        Friend Shared ReadOnly Property tipHostsExecuteAction() As String
            Get
                Return ResourceManager.GetString("tipHostsExecuteAction", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
