'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class English
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NHLGames.English", GetType(English).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3) Add Entry.
        '''</summary>
        Friend Shared ReadOnly Property btnAddHosts() As String
            Get
                Return ResourceManager.GetString("btnAddHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4) Remove Entries.
        '''</summary>
        Friend Shared ReadOnly Property btnCleanHosts() As String
            Get
                Return ResourceManager.GetString("btnCleanHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear.
        '''</summary>
        Friend Shared ReadOnly Property btnClearConsole() As String
            Get
                Return ResourceManager.GetString("btnClearConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy to Clipboard.
        '''</summary>
        Friend Shared ReadOnly Property btnCopyConsole() As String
            Get
                Return ResourceManager.GetString("btnCopyConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2) View Hosts.
        '''</summary>
        Friend Shared ReadOnly Property btnOpenHostsFile() As String
            Get
                Return ResourceManager.GetString("btnOpenHostsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1) Test.
        '''</summary>
        Friend Shared ReadOnly Property btnTestHosts() As String
            Get
                Return ResourceManager.GetString("btnTestHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final Scores.
        '''</summary>
        Friend Shared ReadOnly Property chkShowFinalScores() As String
            Get
                Return ResourceManager.GetString("chkShowFinalScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live Scores.
        '''</summary>
        Friend Shared ReadOnly Property chkShowLiveScores() As String
            Get
                Return ResourceManager.GetString("chkShowLiveScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Series Record.
        '''</summary>
        Friend Shared ReadOnly Property chkShowSeriesRecord() As String
            Get
                Return ResourceManager.GetString("chkShowSeriesRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ending.
        '''</summary>
        Friend Shared ReadOnly Property enumending() As String
            Get
                Return ResourceManager.GetString("enumending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property enumfinal() As String
            Get
                Return ResourceManager.GetString("enumfinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In progress.
        '''</summary>
        Friend Shared ReadOnly Property enuminprogress() As String
            Get
                Return ResourceManager.GetString("enuminprogress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pregame.
        '''</summary>
        Friend Shared ReadOnly Property enumpregame() As String
            Get
                Return ResourceManager.GetString("enumpregame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scheduled.
        '''</summary>
        Friend Shared ReadOnly Property enumscheduled() As String
            Get
                Return ResourceManager.GetString("enumscheduled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [cli].
        '''</summary>
        Friend Shared ReadOnly Property errorCliStreamlink() As String
            Get
                Return ResourceManager.GetString("errorCliStreamlink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Can&apos;t find NHLGames config file. You will have to reinstall NHLGames..
        '''</summary>
        Friend Shared ReadOnly Property errorConfigFile() As String
            Get
                Return ResourceManager.GetString("errorConfigFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error : Failed to deserialize setting value of &apos;{0}&apos; to type &apos;{1}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property errorDeserialize() As String
            Get
                Return ResourceManager.GetString("errorDeserialize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to error:.
        '''</summary>
        Friend Shared ReadOnly Property errorDetection() As String
            Get
                Return ResourceManager.GetString("errorDetection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to :.
        '''</summary>
        Friend Shared ReadOnly Property errorDoubleDot() As String
            Get
                Return ResourceManager.GetString("errorDoubleDot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to exception.
        '''</summary>
        Friend Shared ReadOnly Property errorExceptionDetection() As String
            Get
                Return ResourceManager.GetString("errorExceptionDetection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Failed to fetch games schedule..
        '''</summary>
        Friend Shared ReadOnly Property errorFetchingGames() As String
            Get
                Return ResourceManager.GetString("errorFetchingGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: {0}.
        '''</summary>
        Friend Shared ReadOnly Property errorGeneral() As String
            Get
                Return ResourceManager.GetString("errorGeneral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Can&apos;t find mpv.exe : mpv is a media player that we shipped with NHLGames. You probably moved it or deleted it. Please set a player, NHLGames needs one..
        '''</summary>
        Friend Shared ReadOnly Property errorMpvExe() As String
            Get
                Return ResourceManager.GetString("errorMpvExe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: No media player selected in settings..
        '''</summary>
        Friend Shared ReadOnly Property errorPlayerPathEmpty() As String
            Get
                Return ResourceManager.GetString("errorPlayerPathEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Failed to read app setting: {0}.
        '''</summary>
        Friend Shared ReadOnly Property errorReadingSettings() As String
            Get
                Return ResourceManager.GetString("errorReadingSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Can&apos;t set Ad Detection Modules. Verify if a Nugget package has a dependency of an older nugget package that you have installed (ex: Spotify and Json): {0}.
        '''</summary>
        Friend Shared ReadOnly Property errorSetAdModule() As String
            Get
                Return ResourceManager.GetString("errorSetAdModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error:  Can&apos;t find streamlink.exe. Streamlink is a tool that NHLGames uses to send streams to your media player, we shipped it with NHLGames. You probably moved it or deleted it and if you don&apos;t set any custom path, you will have to put it back there, just drop the folder &apos;streamlink-0.8.1&apos; next to NHLGames.exe..
        '''</summary>
        Friend Shared ReadOnly Property errorStreamlinkExe() As String
            Get
                Return ResourceManager.GetString("errorStreamlinkExe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Unable to decode url from NHL API, the structure has changed. We will have to fix this..
        '''</summary>
        Friend Shared ReadOnly Property errorUnableToDecodeJson() As String
            Get
                Return ResourceManager.GetString("errorUnableToDecodeJson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to unknown (server is not available).
        '''</summary>
        Friend Shared ReadOnly Property errorUnknownServerDown() As String
            Get
                Return ResourceManager.GetString("errorUnknownServerDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Failed to write app settings.
        '''</summary>
        Friend Shared ReadOnly Property errorWritingSettings() As String
            Get
                Return ResourceManager.GetString("errorWritingSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GB/Hour.
        '''</summary>
        Friend Shared ReadOnly Property formatGbHour() As String
            Get
                Return ResourceManager.GetString("formatGbHour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MB/Hour.
        '''</summary>
        Friend Shared ReadOnly Property formatMbHour() As String
            Get
                Return ResourceManager.GetString("formatMbHour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}, {1} {2}, {3}.
        '''</summary>
        Friend Shared ReadOnly Property formatWeekMonthDayYear() As String
            Get
                Return ResourceManager.GetString("formatWeekMonthDayYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1st.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod1() As String
            Get
                Return ResourceManager.GetString("gamePeriod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2nd.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod2() As String
            Get
                Return ResourceManager.GetString("gamePeriod2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3rd.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriod3() As String
            Get
                Return ResourceManager.GetString("gamePeriod3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Final.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodFinal() As String
            Get
                Return ResourceManager.GetString("gamePeriodFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OT.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOt() As String
            Get
                Return ResourceManager.GetString("gamePeriodOt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}OT.
        '''</summary>
        Friend Shared ReadOnly Property gamePeriodOtMore() As String
            Get
                Return ResourceManager.GetString("gamePeriodOtMore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to leads.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesLead() As String
            Get
                Return ResourceManager.GetString("gameSeriesLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tied.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesTied() As String
            Get
                Return ResourceManager.GetString("gameSeriesTied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wins.
        '''</summary>
        Friend Shared ReadOnly Property gameSeriesWin() As String
            Get
                Return ResourceManager.GetString("gameSeriesWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Away Team : {0} {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblAwayTeam() As String
            Get
                Return ResourceManager.GetString("lblAwayTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} camera views.
        '''</summary>
        Friend Shared ReadOnly Property lblCamViews() As String
            Get
                Return ResourceManager.GetString("lblCamViews", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CDN.
        '''</summary>
        Friend Shared ReadOnly Property lblCdn() As String
            Get
                Return ResourceManager.GetString("lblCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} endzone camera.
        '''</summary>
        Friend Shared ReadOnly Property lblEndzoneCam() As String
            Get
                Return ResourceManager.GetString("lblEndzoneCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property lblEnglish() As String
            Get
                Return ResourceManager.GetString("lblEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Français.
        '''</summary>
        Friend Shared ReadOnly Property lblFrench() As String
            Get
                Return ResourceManager.GetString("lblFrench", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to French Canadian stream.
        '''</summary>
        Friend Shared ReadOnly Property lblFrenchNetwork() As String
            Get
                Return ResourceManager.GetString("lblFrenchNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblGame() As String
            Get
                Return ResourceManager.GetString("lblGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GM {0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblGameAbv() As String
            Get
                Return ResourceManager.GetString("lblGameAbv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download MPC.
        '''</summary>
        Friend Shared ReadOnly Property lblGetMpc() As String
            Get
                Return ResourceManager.GetString("lblGetMpc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download VLC.
        '''</summary>
        Friend Shared ReadOnly Property lblGetVlc() As String
            Get
                Return ResourceManager.GetString("lblGetVlc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home Team : {0} {1}.
        '''</summary>
        Friend Shared ReadOnly Property lblHomeTeam() As String
            Get
                Return ResourceManager.GetString("lblHomeTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server&apos;s Hostname.
        '''</summary>
        Friend Shared ReadOnly Property lblHostname() As String
            Get
                Return ResourceManager.GetString("lblHostname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server Hosts Entry.
        '''</summary>
        Friend Shared ReadOnly Property lblHosts() As String
            Get
                Return ResourceManager.GetString("lblHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property lblLanguage() As String
            Get
                Return ResourceManager.GetString("lblLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPC Path.
        '''</summary>
        Friend Shared ReadOnly Property lblMpcPath() As String
            Get
                Return ResourceManager.GetString("lblMpcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPV Path.
        '''</summary>
        Friend Shared ReadOnly Property lblMpvPath() As String
            Get
                Return ResourceManager.GetString("lblMpvPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to National stream.
        '''</summary>
        Friend Shared ReadOnly Property lblNationalNetwork() As String
            Get
                Return ResourceManager.GetString("lblNationalNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No game found.
        '''</summary>
        Friend Shared ReadOnly Property lblNoGames() As String
            Get
                Return ResourceManager.GetString("lblNoGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No stream available.
        '''</summary>
        Friend Shared ReadOnly Property lblNoStreamAvailable() As String
            Get
                Return ResourceManager.GetString("lblNoStreamAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note: Refreshing games is required for CDN change to take effect.
        '''</summary>
        Friend Shared ReadOnly Property lblNoteCdn() As String
            Get
                Return ResourceManager.GetString("lblNoteCdn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  on {0}.
        '''</summary>
        Friend Shared ReadOnly Property lblOnNetwork() As String
            Get
                Return ResourceManager.GetString("lblOnNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output.
        '''</summary>
        Friend Shared ReadOnly Property lblOutput() As String
            Get
                Return ResourceManager.GetString("lblOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Player.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayer() As String
            Get
                Return ResourceManager.GetString("lblPlayer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Players Args.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayerArgs() As String
            Get
                Return ResourceManager.GetString("lblPlayerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Playoffs.
        '''</summary>
        Friend Shared ReadOnly Property lblPlayoffs() As String
            Get
                Return ResourceManager.GetString("lblPlayoffs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preseason.
        '''</summary>
        Friend Shared ReadOnly Property lblPreseason() As String
            Get
                Return ResourceManager.GetString("lblPreseason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stream Quality.
        '''</summary>
        Friend Shared ReadOnly Property lblQuality() As String
            Get
                Return ResourceManager.GetString("lblQuality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Referee camera.
        '''</summary>
        Friend Shared ReadOnly Property lblRefCam() As String
            Get
                Return ResourceManager.GetString("lblRefCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Scores.
        '''</summary>
        Friend Shared ReadOnly Property lblShowScores() As String
            Get
                Return ResourceManager.GetString("lblShowScores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamlink Path.
        '''</summary>
        Friend Shared ReadOnly Property lblSlPath() As String
            Get
                Return ResourceManager.GetString("lblSlPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streams available during pregame.
        '''</summary>
        Friend Shared ReadOnly Property lblStreamAvailableDuringPregame() As String
            Get
                Return ResourceManager.GetString("lblStreamAvailableDuringPregame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamer Args.
        '''</summary>
        Friend Shared ReadOnly Property lblStreamerArgs() As String
            Get
                Return ResourceManager.GetString("lblStreamerArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} stream.
        '''</summary>
        Friend Shared ReadOnly Property lblTeamStream() As String
            Get
                Return ResourceManager.GetString("lblTeamStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VLC Path.
        '''</summary>
        Friend Shared ReadOnly Property lblVlcPath() As String
            Get
                Return ResourceManager.GetString("lblVlcPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Today.
        '''</summary>
        Friend Shared ReadOnly Property lnkCalendarToday() As String
            Get
                Return ResourceManager.GetString("lnkCalendarToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add our server to your hosts file.
        '''</summary>
        Friend Shared ReadOnly Property msgAddHost() As String
            Get
                Return ResourceManager.GetString("msgAddHost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The {0} file is now set back to Read Only.
        '''</summary>
        Friend Shared ReadOnly Property msgAddReadOnly() As String
            Get
                Return ResourceManager.GetString("msgAddReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts: Backing up file: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgBackingHostsFile() As String
            Get
                Return ResourceManager.GetString("msgBackingHostsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version {0} is available! Changes: {1}{2}{3}.
        '''</summary>
        Friend Shared ReadOnly Property msgChangeLog() As String
            Get
                Return ResourceManager.GetString("msgChangeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts: Removing existing entries from hosts file.
        '''</summary>
        Friend Shared ReadOnly Property msgCleanHostsFile() As String
            Get
                Return ResourceManager.GetString("msgCleanHostsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{0}] .
        '''</summary>
        Friend Shared ReadOnly Property msgDateTimeNow() As String
            Get
                Return ResourceManager.GetString("msgDateTimeNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Need help?.
        '''</summary>
        Friend Shared ReadOnly Property msgDiySteps() As String
            Get
                Return ResourceManager.GetString("msgDiySteps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This line needs to be insert in your hosts file : {0}{1} {2}{0}Click on &apos;Open Hosts File&apos; to open the Hosts file and paste (Ctrl+V) that entry line at the end of your Hosts file.{0}Do you want to copy that entry line to your clipboard ?.
        '''</summary>
        Friend Shared ReadOnly Property msgDiyStepsText() As String
            Get
                Return ResourceManager.GetString("msgDiyStepsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading: Game schedule for {0} to {1}.
        '''</summary>
        Friend Shared ReadOnly Property msgDownloadingJsonFile() As String
            Get
                Return ResourceManager.GetString("msgDownloadingJsonFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error happened! See the console for more details.{0}Click on [?] button in the top-right corner to view NHLGames documentation for quick support in the Support section (App and Player).{0}You can also copy the console log using &apos;Copy to clipboard&apos; button and paste it in a new thread on NHLGames subreddit for help. Use the link in the bottom-left corner to get there..
        '''</summary>
        Friend Shared ReadOnly Property msgErrorGeneralText() As String
            Get
                Return ResourceManager.GetString("msgErrorGeneralText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failure.
        '''</summary>
        Friend Shared ReadOnly Property msgFailure() As String
            Get
                Return ResourceManager.GetString("msgFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fetching.
        '''</summary>
        Friend Shared ReadOnly Property msgFetching() As String
            Get
                Return ResourceManager.GetString("msgFetching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fetching: Saved game schedule for {0} ({1}).
        '''</summary>
        Friend Shared ReadOnly Property msgFetchingSavedSchedule() As String
            Get
                Return ResourceManager.GetString("msgFetchingSavedSchedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Games Found : {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgGamesFound() As String
            Get
                Return ResourceManager.GetString("msgGamesFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: Game schedule for {1} from NHL.tv.
        '''</summary>
        Friend Shared ReadOnly Property msgGettingSchedule() As String
            Get
                Return ResourceManager.GetString("msgGettingSchedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames can&apos;t work without having its hostname set in your Windows Hosts file. Do you want to let NHLGames adds an entry to your Hosts file, so Windows can resolve NHLGames hostname and connect to its server&apos;s IP address?.
        '''</summary>
        Friend Shared ReadOnly Property msgHostnameSet() As String
            Get
                Return ResourceManager.GetString("msgHostnameSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts entry doesn&apos;t seem to be working :(.
        '''</summary>
        Friend Shared ReadOnly Property msgHostsFailure() As String
            Get
                Return ResourceManager.GetString("msgHostsFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hosts file looks good!.
        '''</summary>
        Friend Shared ReadOnly Property msgHostsSuccess() As String
            Get
                Return ResourceManager.GetString("msgHostsSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Games.
        '''</summary>
        Friend Shared ReadOnly Property msgLoadingGames() As String
            Get
                Return ResourceManager.GetString("msgLoadingGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Version Available.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionAvailable() As String
            Get
                Return ResourceManager.GetString("msgNewVersionAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new version is available, download the latest version {0} on /r/nhl_games.
        '''</summary>
        Friend Shared ReadOnly Property msgNewVersionText() As String
            Get
                Return ResourceManager.GetString("msgNewVersionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OFF.
        '''</summary>
        Friend Shared ReadOnly Property msgOff() As String
            Get
                Return ResourceManager.GetString("msgOff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ON.
        '''</summary>
        Friend Shared ReadOnly Property msgOn() As String
            Get
                Return ResourceManager.GetString("msgOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refreshing.
        '''</summary>
        Friend Shared ReadOnly Property msgRefreshing() As String
            Get
                Return ResourceManager.GetString("msgRefreshing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove our server from your hosts file.
        '''</summary>
        Friend Shared ReadOnly Property msgRemoveHost() As String
            Get
                Return ResourceManager.GetString("msgRemoveHost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: The {0} file is no longer Read Only.
        '''</summary>
        Friend Shared ReadOnly Property msgRemoveReadOnly() As String
            Get
                Return ResourceManager.GetString("msgRemoveReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admin Access Required.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdmin() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames is missing the required hosts file entry. Do you want to restart this application as an Administrator and add the required entry?.
        '''</summary>
        Friend Shared ReadOnly Property msgRunAsAdminText() As String
            Get
                Return ResourceManager.GetString("msgRunAsAdminText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Failed to download the game schedule file from {0}. Second attempt..
        '''</summary>
        Friend Shared ReadOnly Property msgServerNoRespondTryingAgain() As String
            Get
                Return ResourceManager.GetString("msgServerNoRespondTryingAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Server {0} seems down.
        '''</summary>
        Friend Shared ReadOnly Property msgServerSeemsDown() As String
            Get
                Return ResourceManager.GetString("msgServerSeemsDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Setting updated for &apos;{0}&apos; to &apos;{1}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property msgSettingUpdated() As String
            Get
                Return ResourceManager.GetString("msgSettingUpdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting: {0} {1}.
        '''</summary>
        Friend Shared ReadOnly Property msgStartingApp() As String
            Get
                Return ResourceManager.GetString("msgStartingApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Success.
        '''</summary>
        Friend Shared ReadOnly Property msgSuccess() As String
            Get
                Return ResourceManager.GetString("msgSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} vs {1}.
        '''</summary>
        Friend Shared ReadOnly Property msgTeamVsTeam() As String
            Get
                Return ResourceManager.GetString("msgTeamVsTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test the hosts file.
        '''</summary>
        Friend Shared ReadOnly Property msgTestHosts() As String
            Get
                Return ResourceManager.GetString("msgTestHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test ability to write to this directory.
        '''</summary>
        Friend Shared ReadOnly Property msgTestTxtContent() As String
            Get
                Return ResourceManager.GetString("msgTestTxtContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} enable.
        '''</summary>
        Friend Shared ReadOnly Property msgThisEnable() As String
            Get
                Return ResourceManager.GetString("msgThisEnable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Value too large for display].
        '''</summary>
        Friend Shared ReadOnly Property msgValueTooLarge() As String
            Get
                Return ResourceManager.GetString("msgValueTooLarge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Hosts File.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHosts() As String
            Get
                Return ResourceManager.GetString("msgViewHosts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to view the changes NHLGames made to your Hosts file?.
        '''</summary>
        Friend Shared ReadOnly Property msgViewHostsText() As String
            Get
                Return ResourceManager.GetString("msgViewHostsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Video On Demand Status: {0}.
        '''</summary>
        Friend Shared ReadOnly Property msgVOD() As String
            Get
                Return ResourceManager.GetString("msgVOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Console.
        '''</summary>
        Friend Shared ReadOnly Property tabConsole() As String
            Get
                Return ResourceManager.GetString("tabConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Games.
        '''</summary>
        Friend Shared ReadOnly Property tabGames() As String
            Get
                Return ResourceManager.GetString("tabGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modules.
        '''</summary>
        Friend Shared ReadOnly Property tabModules() As String
            Get
                Return ResourceManager.GetString("tabModules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property tabSettings() As String
            Get
                Return ResourceManager.GetString("tabSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NHLGames Official Bug Report {1}{0}{0}OS : {2} {3}{0}{0}UI loaded : {4}{0}{0}Domain resolved : {5}{0}{0}Server IP found : {6}{0}{0}Selected hostname : {7}{0}{0}Selected player : {8}{0}{0}Streamlink path : {9} [=UI:{10}]{0}{0}VLC path : {11} [=UI:{12}]{0}{0}MPC path : {13} [=UI:{14}]{0}{0}MPV path : {15} [=UI:{16}]{0}{0}Console log : {0}{0}{17}.
        '''</summary>
        Friend Shared ReadOnly Property textCopyConsole() As String
            Get
                Return ResourceManager.GetString("textCopyConsole", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
